spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - profile
              - email
          naver:
            client-id:
            client-secret:
            client-name: Naver
            redirect-uri: "http://localhost:9090/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id:
            client-secret:
            client-name: Kakao
            client-authentication-method: POST
            redirect-uri: "http://localhost:9090/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



