
  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 181404396789-us9cctunfqcgjcnslf6ho60tbuam2k7p.apps.googleusercontent.com
              client-secret: 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
              scope:
                - profile
                - email
            naver:
              client-id: s_lDyWrVuV9SO2QjACJY
              client-secret: 7z1NTrQTPt
              client-name: Naver
              redirect-uri: "http://localhost:9090/login/oauth2/code/naver"
              authorization-grant-type: authorization_code
              scope:
                - name
                - email
            kakao:
              client-id: ae2276b6418b550017a9030c73ce8834
              client-secret: PU3ARhRfCNJiyrqBOePUsRpYnDO02Snl
              client-name: Kakao
              client-authentication-method: POST
              redirect-uri: "http://localhost:9090/login/oauth2/code/kakao"
              authorization-grant-type: authorization_code
              scope:
                - profile_nickname
                - account_email


          provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id

